[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://6kt29kkeub.execute-api.eu-central-1.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
